import chidambaramImg from'./assets/chidambaram.png';
import kumbakonamImg from'./assets/kumbakonam.png';
import masangudiImg from'./assets/masangudi.png';
import pollachiImg from'./assets/pollachi.png';
import thanjavurImg from'./assets/thanjavur.png';
import tirunelveliImg from'./assets/tirunelveli.png';
 
export const cardData = [
    {
        cityName:'Chidambaram',
        cityOneLine:'Catching a Short Break at the Lotus Pond',
        cityImg:chidambaramImg,
        cityDesciption:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat.Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat.',
        cityFullDescription:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. ',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. ',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. '],
        cityTemperature:'32˚C'
    },
    {
        cityName:'Kumbakonam',
        cityOneLine:'Fall in love with the divine agraharams',
        cityImg:kumbakonamImg,
        cityDesciption:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat.',
        cityFullDescription:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. ',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. ',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. '],
        cityTemperature:'32˚C'
    },
    {
        cityName:'Masangudi',
        cityOneLine:'Road Trip enroute the mountains and forest',
        cityImg:masangudiImg,
        cityDesciption:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat.',
        cityFullDescription:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. ',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. ',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. '],
        cityTemperature:'32˚C'
    },
    {
        cityName:'Pollachi',
        cityOneLine:'Never Ending Paddy Fields and Narrow Roads',
        cityImg:pollachiImg,
        cityDesciption:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat.',
        cityFullDescription:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. ',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. ',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. '],
        cityTemperature:'32˚C'
    },
    {
        cityName:'Thanjavur',
        cityOneLine:'Small Ride across town in mid summer heat',
        cityImg:thanjavurImg,
        cityDesciption:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat.',
        cityFullDescription:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. ',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. ',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. '],
        cityTemperature:'32˚C'
    },
    {
        cityName:'Thirunelveli',
        cityOneLine:'Energy driven drive through the windmills',
        cityImg:tirunelveliImg,
        cityDesciption:'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat.',
        cityFullDescription:['Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. ',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. ',
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad ipsa, rem porro deleniti, explicabo accusamus magni consequatur ducimus eius qui quae accusantium ipsam excepturi odit voluptatem a, quasi molestiae fugiat. '],
        cityTemperature:'32˚C'
    }
]